<!DOCTYPE html>                                                                                                                                                                                                                                                                      
<html>                                                                                                                                                                                                                                                                               
 <head>                                                                                                                                                                                                                                                                              
  <title></title>                                                                                                                                                                                                                                                                    
  <meta name="viewport" content="user-scalable=0,minimum-scale=1.0, maximum-scale=1.0" />                                                                                                                                                                                            
  <style type="text/css"> body {margin: 0; overflow: hidden;} </style>                                                                                                                                                                                                               
 </head>                                                                                                                                                                                                                                                                             
 <body>                                                                                                                                                                                                                                                                              
  <style>.im_1664_ads-lbl,.im_1664_ads-lbl img{position:absolute;bottom:0;right:                                                                                                                                                                                                     
0;pointer-events:none;z-index:1000000000000000}.im_1664_ads-lbl img{width:26px;height:16px}</style>                                                                                                                                                                                  
  <div class="im_1664_ads-lbl">                                                                                                                                                                                                                                                      
   <img src="http://160.19.50.107/adimg/AdsiconHDPI1472034285.png" />                                                                                                                                                                                                                
  </div>                                                                                                                                                                                                                                                                             
  <style> .inmC { margin-left: auto; margin-right: auto; display: block; }                                                                                                                                                                                                           
</style>                                                                                                                                                                                                                                                                             
  <a href="http://119.23.48.82/adimg/adclick.do" target="_top" style="text-decoration:none;"><img border="0" class="inmC" src="http://160.19.50.107/adimg/3617be5e-d4ce-4f49-9d3e-5519fbecb830.jpeg" alt="苏宁易购-双十一网购11天，20亿购物红包等你领" height="50" width="320" /></a>
  <style>body{margin:0}</style>                                                                                                                                                                                                                                                      
 </body>                                                                                                                                                                                                                                                                             
</html>                                                                                                                                                                                                                                                                              